### PR TITLE
Added a createResult Method to Dispatcher

### PR DESCRIPTION
**Pull request by hco**
This allows implementing your own way of retrieving a result from a controller, without overriding the whole run() method.

### CODE REVIEW

**Comment by derickr** [comment]
Do you have a test case?

**Comment by hco** [comment]
Nope - it is covered by existing test cases, isn't it?
Or do you mean a test case that verifies that the overriden method is actually being called?

**Comment by derickr** [comment]
Yeah - the latter :-) (Sorry for being slow, I was on holiday)

**Comment by hco** [comment]
Sorry, I forgot to mention this, but I added tests a while ago.

**Pull request merged**
